# Change these first
owner: extratone # Your GitHub username
repo: up # Your Github repository name
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

# Add your sites here
sites:
  - name: Extratone
    url: https://www.extratone.com
  - name: Bilge
    url: https://bilge.world
  - name: ~
    url: https://tilde.town/~extratone
  - name: UIKeyCommand
    url: https://uikeycommand.com
  - name: Honk
    url: https://dieselgoth.com
  - name: Chaff
    url: https://chaff.writeas.com/
  - name: Iowa
    url: https://iowa.neocities.org

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /up
  logoUrl: https://i.snap.as/lBCNqyG.png
  name: Up!
  introTitle: "UP - EXTRANET STATUS"
  introMessage: This is an uptime monitor for the Extranet.
  theme: dark
  navbar:
    - title: Extranet Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
